
# Default application configuration that all configurations inherit from.

linters:

  BorderZero:
    enabled: true
    convention:  none

  ChainedClasses:
    enabled: true

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: true
    allowed: '^[/** ]'
    style: silent

  IdSelector:
    enabled: false

#  Indentation:
#    enabled: true
#    allow_non_nested_indentation: false
#    character: space # or 'tab'
#    width: 2

  HexLength:
    enabled: true
    style:  long

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  ImportantRule:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero '

  NestingDepth:
    enabled: false
    max_depth: 3
    ignore_parent_selectors: false

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false

  VendorPrefix:
    enabled: false
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []
